spring:
  datasource:
    url: jdbc:mysql://mysql:3306/krampoline?useSSL=false&allowPublicKeyRetrieval=TRUE&user=root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

logging:
  level:
    '[com.example.kakao]': INFO
    '[org.hibernate.type]': TRACE